import type { RagListItem } from "./types";

export const mockRagItems: RagListItem[] = [
  {
    id: "kb-product",
    name: "产品知识库",
    description: "沉淀产品功能、版本说明和常见问题。",
    icon: "BookOpen",
    documentCount: 12,
    chunkCount: 186,
    topK: 5,
    similarityThreshold: 0.7,
    status: "active",
    updatedAt: "2026-05-28T10:30:00.000Z",
  },
  {
    id: "kb-sales",
    name: "销售话术库",
    description: "用于销售场景的问答、异议处理和行业案例。",
    icon: "BriefcaseBusiness",
    documentCount: 8,
    chunkCount: 94,
    topK: 6,
    similarityThreshold: 0.72,
    status: "active",
    updatedAt: "2026-05-26T09:15:00.000Z",
  },
  {
    id: "kb-support-disabled",
    name: "客服归档库",
    description: "历史客服知识归档，当前暂停使用。",
    icon: "Archive",
    documentCount: 20,
    chunkCount: 260,
    topK: 5,
    similarityThreshold: 0.68,
    status: "disabled",
    updatedAt: "2026-05-20T14:00:00.000Z",
  },
  {
    id: "kb-empty-active",
    name: "新业务知识库",
    description: "用于新业务资料准备，暂未上传文档。",
    icon: "Lightbulb",
    documentCount: 0,
    chunkCount: 0,
    topK: 5,
    similarityThreshold: 0.7,
    status: "active",
    updatedAt: "2026-05-29T08:00:00.000Z",
  },
];
