// RAG 内部策略参数集中放这里，避免 topK、阈值等实现细节泄漏给调用方。
export const RAG_CONFIG = {
  fastTopK: 3,
  topK: 5,
  detailedTopK: 8,
  candidateMultiplier: 4,
  vectorMinScore: 0.01,
  minScore: 0.2,
  fallbackTop1Score: 0.05,
  enableFallbackTop1: true,
  maxContextChars: 6000,
  rrfK: 60,
  bm25TitleWeight: 2,
  bm25SummaryWeight: 1.5,
  bm25ContentWeight: 1,
  exactTermSearchEnabled: true,
  exactTitleWeight: 3,
  exactSummaryWeight: 1.8,
  exactContentWeight: 1,
  exactMetadataWeight: 0.6,
  exactPhraseWeight: 3,
  maxExactTerms: 12,
  queryExpansionEnabled: true,
  maxExpandedQueries: 4,
  llmQueryRewriteEnabled: false,
  maxLlmRewrittenQueries: 3,
  llmQueryRewriteFailOpen: true,
  rulesRerankEnabled: true,
  rulesRerankBaseWeight: 0.7,
  rulesRerankBoostWeight: 0.3,
  rulesTitleMatchWeight: 3,
  rulesSummaryMatchWeight: 2,
  rulesContentMatchWeight: 1,
  rulesMetadataMatchWeight: 0.6,
  rulesPhraseMatchWeight: 2,
  rulesExactSourceBoost: 0.2,
  rulesHybridSourceBoost: 0.15,
  rulesIntentChunkTypeBoost: 0.35,
  rulesFreshnessBoost: 0.05,
  rulesFreshnessMinGapDays: 7,
  maxRulesRerankTerms: 16,
  mmrEnabled: true,
  mmrLambda: 0.7,
  adjacentExpansionEnabled: true,
  adjacentWindowByMode: {
    fast: 0,
    balanced: 1,
    detailed: 1,
  },
  maxAdjacentExtraChunksByMode: {
    fast: 0,
    balanced: 4,
    detailed: 8,
  },
  adjacentScoreDecay: 0.92,
} as const;
