import type { KnowledgeChunk } from "@/features/rag/types";

const now = "2026-05-29T10:00:00.000Z";

// 阶段 1 使用这批数据跑通接口闭环；后续替换成 DB + 向量索引读取时，保持 KnowledgeChunk 字段不变。
export const mockKnowledgeChunks: KnowledgeChunk[] = [
  {
    id: "chunk_wiki_001",
    knowledgeBaseId: "kb_001",
    knowledgeId: "wiki_001",
    title: "账号权限配置说明",
    content: "管理员可以在系统设置中进入权限管理页面，为成员分配不同角色。常见角色包括管理员、编辑者和普通成员。",
    summary: "说明账号权限和角色配置方式",
    categoryId: "cat_permission",
    tagIds: ["tag_admin", "tag_permission"],
    status: "available",
    sourceType: "wiki",
    chunkType: "wiki",
    chunkIndex: 0,
    sourceChunkIds: ["chunk_doc_001", "chunk_doc_002"],
    metadata: {
      sectionPath: "账号管理/权限配置",
      sourceKnowledgeIds: ["doc_001", "doc_002"],
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "chunk_doc_001",
    knowledgeBaseId: "kb_001",
    knowledgeId: "doc_001",
    title: "权限管理操作手册",
    content: "进入系统设置后，选择成员管理，点击目标成员右侧的角色按钮，即可修改该成员的权限。保存后权限会立即生效。",
    summary: "成员权限修改步骤",
    categoryId: "cat_permission",
    tagIds: ["tag_admin", "tag_member"],
    status: "available",
    sourceType: "file",
    chunkType: "text",
    chunkIndex: 0,
    nextChunkId: "chunk_doc_002",
    metadata: {
      fileName: "权限管理操作手册.md",
      sectionPath: "成员管理/修改角色",
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "chunk_doc_002",
    knowledgeBaseId: "kb_001",
    knowledgeId: "doc_001",
    title: "权限管理操作手册",
    content: "普通成员不能访问管理员专属页面。删除知识库、审核知识、修改权限等操作需要管理员角色。",
    summary: "管理员专属操作范围",
    categoryId: "cat_permission",
    tagIds: ["tag_admin", "tag_permission"],
    status: "available",
    sourceType: "file",
    chunkType: "text",
    chunkIndex: 1,
    prevChunkId: "chunk_doc_001",
    metadata: {
      fileName: "权限管理操作手册.md",
      sectionPath: "成员管理/权限边界",
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "chunk_rag_001",
    knowledgeBaseId: "kb_rag",
    knowledgeId: "doc_rag_001",
    title: "RAG 检索开发技术方案",
    content: "RAG 检索初版先使用 mock 数据跑通闭环，再逐步接入 embedding、向量检索、BM25 混合检索和离线评测。",
    summary: "RAG 检索开发路线",
    categoryId: "cat_rag",
    tagIds: ["tag_rag", "tag_retrieval"],
    status: "available",
    sourceType: "manual",
    chunkType: "summary",
    chunkIndex: 0,
    metadata: {
      sectionPath: "开发阶段规划",
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "chunk_disabled_001",
    knowledgeBaseId: "kb_001",
    knowledgeId: "doc_disabled_001",
    title: "旧版权限说明",
    content: "这是一段已禁用的旧版权限说明，检索模块不应返回它。",
    status: "disabled",
    sourceType: "file",
    chunkType: "text",
    chunkIndex: 0,
    createdAt: now,
    updatedAt: now,
  },
];
